<?php

namespace Mike\AdventOfCode\Solutions\Year2016\Day11;

class PeriodicTable
{
    /**
     * The elements of the elements of the periodic table.
     */
    public static array $elements = [
        'H' => 'Hydrogen',
        'He' => 'Helium',
        'Li' => 'Lithium',
        'Be' => 'Beryllium',
        'B' => 'Boron',
        'C' => 'Carbon',
        'N' => 'Nitrogen',
        'O' => 'Oxygen',
        'F' => 'Fluorine',
        'Ne' => 'Neon',
        'Na' => 'Sodium',
        'Mg' => 'Magnesium',
        'Al' => 'Aluminum',
        'Si' => 'Silicon',
        'P' => 'Phosphorus',
        'S' => 'Sulfur',
        'Cl' => 'Chlorine',
        'Ar' => 'Argon',
        'K' => 'Potassium',
        'Ca' => 'Calcium',
        'Sc' => 'Scandium',
        'Ti' => 'Titanium',
        'V' => 'Vanadium',
        'Cr' => 'Chromium',
        'Mn' => 'Manganese',
        'Fe' => 'Iron',
        'Co' => 'Cobalt',
        'Ni' => 'Nickel',
        'Cu' => 'Copper',
        'Zn' => 'Zinc',
        'Ga' => 'Gallium',
        'Ge' => 'Germanium',
        'As' => 'Arsenic',
        'Se' => 'Selenium',
        'Br' => 'Bromine',
        'Kr' => 'Krypton',
        'Rb' => 'Rubidium',
        'Sr' => 'Strontium',
        'Y' => 'Yttrium',
        'Zr' => 'Zirconium',
        'Nb' => 'Niobium',
        'Mo' => 'Molybdenum',
        'Tc' => 'Technetium',
        'Ru' => 'Ruthenium',
        'Rh' => 'Rhodium',
        'Pd' => 'Palladium',
        'Ag' => 'Silver',
        'Cd' => 'Cadmium',
        'In' => 'Indium',
        'Sn' => 'Tin',
        'Sb' => 'Antimony',
        'Te' => 'Tellurium',
        'I' => 'Iodine',
        'Xe' => 'Xenon',
        'Cs' => 'Cesium',
        'Ba' => 'Barium',
        'La' => 'Lanthanum',
        'Ce' => 'Cerium',
        'Pr' => 'Praseodymium',
        'Nd' => 'Neodymium',
        'Pm' => 'Promethium',
        'Sm' => 'Samarium',
        'Eu' => 'Europium',
        'Gd' => 'Gadolinium',
        'Tb' => 'Terbium',
        'Dy' => 'Dysprosium',
        'Ho' => 'Holmium',
        'Er' => 'Erbium',
        'Tm' => 'Thulium',
        'Yb' => 'Ytterbium',
        'Lu' => 'Lutetium',
        'Hf' => 'Hafnium',
        'Ta' => 'Tantalum',
        'W' => 'Tungsten',
        'Re' => 'Rhenium',
        'Os' => 'Osmium',
        'Ir' => 'Iridium',
        'Pt' => 'Platinum',
        'Au' => 'Gold',
        'Hg' => 'Mercury',
        'Tl' => 'Thallium',
        'Pb' => 'Lead',
        'Bi' => 'Bismuth',
        'Po' => 'Polonium',
        'At' => 'Astatine',
        'Rn' => 'Radon',
        'Fr' => 'Francium',
        'Ra' => 'Radium',
        'Ac' => 'Actinium',
        'Th' => 'Thorium',
        'Pa' => 'Protactinium',
        'U' => 'Uranium',
        'Np' => 'Neptunium',
        'Pu' => 'Plutonium',
        'Am' => 'Americium',
        'Cm' => 'Curium',
        'Bk' => 'Berkelium',
        'Cf' => 'Californium',
        'Es' => 'Einsteinium',
        'Fm' => 'Fermium',
        'Md' => 'Mendelevium',
        'No' => 'Nobelium',
        'Lr' => 'Lawrencium',
        'Rf' => 'Rutherfordium',
        'Db' => 'Dubnium',
        'Sg' => 'Seaborgium',
        'Bh' => 'Bohrium',
        'Hs' => 'Hassium',
        'Mt' => 'Meitnerium',
        'Ds' => 'Darmstadtium',
        'Rg' => 'Roentgenium',
        'Cn' => 'Copernicium',
        'Nh' => 'Nihonium',
        'Fl' => 'Flerovium',
        'Mc' => 'Moscovium',
        'Lv' => 'Livermorium',
        'Ts' => 'Tennessine',
        'Og' => 'Oganesson',
    ];

    /**
     * Get the symbol from element name.
     */
    public static function symbol(string $name): string|null
    {
        return array_search(ucfirst(strtolower($name)), static::$elements) ?: null;
    }

    /**
     * Get the name of the element from its symbol.
     */
    public static function name(string $symbol): string|null
    {
        return static::$elements[ucfirst(strtolower($symbol))] ?? null;
    }
}
